### PR TITLE
Add support of uintN to dataframe

### PR DESCRIPTION
**Pull request by plummm**
I've encountered issue with `dataframe_from_result_table()` when the data type in Kusto table is `uint`. The current dataframe does not support uint type, this patch adds support of uint, uint32, uint64. FYI, pandas dataframe also support 8 bits, for some reason the original design doesn't support int8 so I didn't add uint8 either.

### Added
Adding support of uint, uint32, uint64 to dataframe.

### CODE REVIEW

**Comment by AsafMah** [comment]
These types should be long deprecated, what command did you run?

**Comment by plummm** [comment]
> These types should be long deprecated, what command did you run?
Hi,

Simple command
```
query = """TableName
| take 10"""
response = client.execute(db, query)
df = dataframe_from_result_table(response.primary_results[0])
```

One of the column is uint type as returned. it raise exception in `dataframe_from_result_table()`.

Do you mean these types were long deprecated in Kusto or pandas? Cuz I still see these types in pandas dataframe.

**Comment by AsafMah** [comment]
In Kusto.

What does the schema of the table looks like ( `.show table TableName cslschema`)

**Comment by plummm** [comment]
Hi,
The results shows one of the column is indeed `uint` 

Scraped results:
`TableName: XXXX, Confidence:uint, XXXX`

This Kusto table have existed for many years, it might have never been upgraded since then.

**Comment by yogilad** [comment]
Hi @plummm ,
These types are long deprecated, and we do not want to continue supporting them in the SDKs.
please use the below guide to migrate relevant columns to supported data types.

[.alter column command - Azure Data Explorer & Real-Time Intelligence | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fdata-explorer%2Fkusto%2Fmanagement%2Falter-column%23changing-column-type-without-data-loss&data=05%7C02%7CYochai.Gilad%40microsoft.com%7C2bac88f5c5e5493bb30a08dcabd3556e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638574171381354823%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=XC4qUNhZP%2Fhh%2F%2FT5AhkJwu7dAnA4TloQOSpPykAs1M4%3D&reserved=0) (see Changing Column Type without Data Loss)

**Pull request closed without merging**
